title: Shrikant Shinde
logo: https://github.com/Bug10101/Image/blob/master/WhatsApp%20Image%202024-05-02%20at%204.36.15%20PM.jpeg
description: Web Application Penetration Tester
show_downloads: true
theme: jekyll-theme-minimal
