title: Shrikant Shinde
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.villadellequerce.it%2F%3Fu%3Dhow-to-become-a-penetration-tester-the-ultimate-2023-dd-wx4d92hM&psig=AOvVaw2AVlZtpPV4oRtlWHsCnBp4&ust=1714803797808000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNDZx5bs8IUDFQAAAAAdAAAAABAP
description: Web Application Penetration Tester
show_downloads: true
theme: jekyll-theme-minimal
