title: Shrikant Shinde
logo: https://media.licdn.com/dms/image/D4D03AQHO1vJhLJm-DQ/profile-displayphoto-shrink_200_200/0/1714648137977?e=2147483647&v=beta&t=zV3SM-ae-XyBJPyWNAf7nvh548-uCvcuBngH9c1C6rI
description: Web Application Penetration Tester
show_downloads: true
theme: jekyll-theme-minimal
